[book]
title = "The Bevy Book"
description = "系统性的 Bevy 游戏引擎中文教程"
language = "zh-CN"
src = "src"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"

[output.html.fold]
enable = true
level = 1
